# Generated by Django 3.1.7 on 2021-05-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Position',
            fields=[
                ('candidate_position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interestId', models.IntegerField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listId', models.IntegerField(primary_key=True, serialize=False)),
                ('listName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCandidate', models.BooleanField(default=False)),
                ('studentIdNumber', models.CharField(max_length=11)),
                ('faculty', models.CharField(max_length=200)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('universityid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stelaapp.profile')),
                ('photo', models.ImageField(null=True, upload_to='cars')),
                ('aboutMe', models.CharField(max_length=500)),
                ('solutions', models.CharField(max_length=500)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('interestsId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.interests')),
                ('listId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.list')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stelaapp.candidate_position')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(db_column='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.university'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stelaapp.candidate_position')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stelaapp.candidate')),
            ],
        ),
    ]
