# Generated by Django 3.1.7 on 2021-05-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='interestsId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.interests'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='listId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stelaapp.list'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(null=True, upload_to='cars'),
        ),
    ]
