# Generated by Django 3.1.7 on 2021-05-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0004_candidate_solutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='profile',
        ),
    ]
