# Generated by Django 3.1.7 on 2021-05-27 11:51

from django.db import migrations, models
import stela.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0004_auto_20210527_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=stela.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
