# Generated by Django 3.1.7 on 2021-05-27 16:28

from django.db import migrations, models
import stela.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0005_auto_20210527_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, null=True, storage=stela.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
