# Generated by Django 3.1.7 on 2021-05-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0005_auto_20210523_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stelaapp.profile'),
        ),
    ]
