# Generated by Django 3.1.7 on 2021-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0006_auto_20210523_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
