# Generated by Django 3.1.7 on 2021-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stelaapp', '0010_auto_20210527_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, default='static images/default_photo.png', null=True, upload_to=''),
        ),
    ]
